format_version: 10
pipelines:
  pipleine_name_here2:
    group: defaultGroup
    template: test_template
    environment_variables:
      srwr_env: prod
      svc_name: tips
    materials:
      material_name2:
        git: https://github.com/bishtmaniish/gocd-code-repo.git
        includes:
        - devops/k8sdevyml/tips/tips-service-api-deployment.yml
        shallow_clone: false
        auto_update: true
        branch: main
