format_version: 10
pipelines:
  gocd-pipeline-with-code-repo-poc:
    group: defaultGroup
    template: repo-build-from-git
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      GoCD-Code-Repo-POC:
        git: https://github.com/bishtmaniish/gocd-code-repo.git
        shallow_clone: true
        auto_update: true
        branch: main
