format_version: 10
pipelines:
  testing_specific_file_changes:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-28c972e:
        git: https://github.com/bishtmaniish/gocd-code-repo.git
        includes:
        - devops/k8sdevyml/tips/tips-service-api-deployment.yml
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - deploying:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -l
                command: ls
                run_if: passed
            - exec:
                command: pwd
                run_if: passed
            - exec:
                arguments:
                - status
                command: git
                run_if: passed
            - exec:
                arguments:
                - remote
                - -v
                command: git
                run_if: passed
